### ISSUE TITLE
refashion into library

### ISSUE THREAD

**Issue by flying-sheep** [jrnewell/goog-webfont-dl#10]
separate CLI and library parts so other packages can use this one as library. if you’re interested but don’t want to do it, i can try my hand at it.

we should also check out https://github.com/Mika-/grunt-google-fonts and include things it can do and we can’t.

**Comment by flying-sheep** [comment]
awesome! now we just need to cut a release and bam!

**Comment by jrnewell** [comment]
Completely off topic... is it just me or does the 'subset' option not work any more (e.g. cyrillic)?  It seems like that this user-agent change broke it:  https://github.com/jrnewell/goog-webfont-dl/commit/fbbf9a6e6a3418de284465bfa7e681783e392c53.  What do you think, should I roll that change back?

**Comment by flying-sheep** [comment]
grunt-google-fonts has [those](https://github.com/Mika-/grunt-google-fonts/blob/597ecf9fc9ec0fdb3b90025fa157044cccaaf086/tasks/index.js#L25-L31) user agents.

maybe we should add unit tests checking if everything works for every format? and if something doesn’t, try grunt-google-font’s solution?

i don’t know much about the google fonts API, e.g. why we need special user agents at all…

**Comment by jrnewell** [comment]
weird, they have something similar to my old user-agent string, but when I tried it just now - google fonts returned woff instead of woff2.

Google webfonts only returns fonts that it thinks are compatible with your system.  That is why we fake different user agents to get all the different types available.

**Comment by flying-sheep** [comment]
shouldn’t it then return whatever the fuck we want if we give it something it doesn’t know? or provide a “give us everything, we know what we’re doing” user agent? 😞
