### ISSUE TITLE
Support for Google Fonts where the font name has a space between words

### ISSUE THREAD

**Issue by eobeda** [jrnewell/goog-webfont-dl#4]
I was hoping that you might have found an elegant work around for the various font names with spaces. Examples include Open Sans or Roboto Condensed.

Google appears to have decided to encode the font names that include spaces with a plus sign (+). As shown here:

link href='http://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'
link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'

I've tried spaces, plus signs(+) and a few others, but they all come back from "querystring.escape" in an encoding that produces an incorrect url for the Google Font.

var url = "http://fonts.googleapis.com/css?family=" + querystring.escape(commander.font) + ":" + commander.styles;

Any ideas on a way to download these ?
Thanks for your insights
Ed

**Comment by jrnewell** [comment]
Does putting the name in quotes work for you?
```shell
goog-webfont-dl -a -f "Open Sans"
```
