### ISSUE TITLE
backslashes in css under windows

### ISSUE THREAD

**Issue by HansHammel** [jrnewell/goog-webfont-dl#5]
On windows
this command

	goog-webfont-dl -d "./client/vendors/googlefonts" -a -f "Aldrich" -o "./client/vendors/googlefonts/Aldrich.css" -p "../vendors/googlefonts/"

gives me this output for css. note the INVALID backslashes in the url - i think the url need also to be in quotation marks !?

	@font-face {
	  font-family: 'Aldrich';
	  font-style: normal;
	  font-weight: 400;
	  src: url(..\vendors\googlefonts\Aldrich.eot);
	  src: local('Aldrich'), url(..\vendors\googlefonts\Aldrich.svg#Aldrich) format('svg'), url(..\vendors\googlefonts\Aldrich.eot?#iefix) format('embedded-opentype'), url(..\vendors\googlefonts\Aldrich.woff2) format('woff2'), url(..\vendors\googlefonts\Aldrich.ttf) format('truetype'), url(..\vendors\googlefonts\Aldrich.woff) format('woff');
	}

**Comment by jrnewell** [comment]
Go catch... I guess I forgot that Windows uses a different set of path utility functions than Linux/OS X. I am kind of abusing the fact that the posix file path handling is basically the same for URLs. I will put in a fix to force the use of posix path handling.

**Comment by HansHammel** [comment]
thx
